### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Botspot** [actionschnitzel/PiGro-Aid-#47]
I recently tried PiGro and had a few suggestions to make.

- In `install.sh`, you can substantially speed up execution-time by installing all of the apt-packages at once.
    ```bash
    sudo apt-get install xterm python3-pil python3-pil.imagetk python3-pip mpg123 lolcat -y
    pip3 install psutil distro
    ```
- Several scripts refer to `/home/pi`. This will cause problems for anybody who is using any different username other than `pi`. I suggest you make use of the `$HOME` environment variable.
- For the 7000 people who have installed PiGro from Pi-Apps, all dependencies really should have been installed by Pi-Apps, rather than during first launch of PiGro. Please open a PR on the Pi-Apps repo to install `xterm python3-pil python3-pil.imagetk python3-pip mpg123 lolcat`.
- For overclocking, `over_voltage` can actually go all the way to `16`. I currently have mine set at 14, and it's super stable.

**Comment by actionschnitzel** [comment]
I've planned the next big update for the beginning of March. By then I will have added your changes :-).
Regarding over_voltage... I sometimes have the feeling it's a gamble how high you can go. I have Pi's that run wonderfully with "8" and others don't boot at all. I think I add additional entry boxes like in Commander-Pi. So that experienced users can change the values themselves.
